"""Writes analysis results to output/analysis.json and output/returns.csv."""

from __future__ import annotations

import csv
import json
import sqlite3
from pathlib import Path

from src.config import OUTPUT_DIR, PROJECT_ROOT

DASHBOARD_DATA_PATH = PROJECT_ROOT / "dashboard" / "data.js"


def export_analysis_json(analysis: dict, path: Path = OUTPUT_DIR / "analysis.json") -> Path:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        json.dump(analysis, f, indent=2, ensure_ascii=False)
    return path


def export_dashboard_data(analysis: dict, path: Path = DASHBOARD_DATA_PATH) -> Path:
    """Writes the same analysis as a JS variable the dashboard loads via <script>.

    A double-clicked HTML file opens under the file:// scheme, where fetch() of a
    local JSON file is blocked by CORS in most browsers (Chrome in particular) even
    for files in the same folder. Embedding the data as a plain <script> sidesteps
    that entirely, so the dashboard truly works with no server.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    # Compact, not indent=2 -- this file is never hand-read (comment below says as
    # much), and pretty-printing years of daily BTC/Fear&Greed history here nearly
    # doubled its size for zero benefit, on top of bloating every daily CI diff.
    body = json.dumps(analysis, ensure_ascii=False, separators=(",", ":"))
    with path.open("w", encoding="utf-8") as f:
        f.write("// Auto-generated by `python main.py analyze` -- do not edit by hand.\n")
        f.write(f"window.ANALYSIS_DATA = {body};\n")
    return path


def export_returns_csv(conn: sqlite3.Connection, path: Path = OUTPUT_DIR / "returns.csv") -> Path:
    """Flat table: one row per (tenure, milestone) return, joined with coin metadata."""
    rows = conn.execute(
        """
        SELECT
            c.coin_id, c.symbol, c.name, c.category,
            t.tenure_id, t.entry_date, t.entry_price, t.entry_rank,
            t.exit_date, t.exit_price, t.days_in_top50, t.has_gap,
            r.milestone_day, r.price_at_day, r.return_pct, r.exited_before_milestone
        FROM tenures t
        JOIN coins c ON c.coin_id = t.coin_id
        LEFT JOIN returns r ON r.tenure_id = t.tenure_id
        ORDER BY c.coin_id, t.entry_date, r.milestone_day
        """
    ).fetchall()

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(
            [
                "coin_id", "symbol", "name", "category",
                "tenure_id", "entry_date", "entry_price", "entry_rank",
                "exit_date", "exit_price", "days_in_top50", "has_gap",
                "milestone_day", "price_at_day", "return_pct", "exited_before_milestone",
            ]
        )
        for row in rows:
            writer.writerow(list(row))
    return path
